catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import home, contacts, CatalogDetailView, CatalogListView, BlogDetailView, BlogView, BlogUpdateView, \
    BlogCreateView, BlogDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contact'),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('product/<int:pk>/', cache_page(60)(CatalogDetailView.as_view()), name='product'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_article',),
    path('blog/update/<str:slug>/', BlogUpdateView.as_view(), name='blog_update',),
    path('blog/delete/<str:slug>/', BlogDeleteView.as_view(), name='blog_delete',),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete',),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, wait_confirm_email, ConfirmPage, UserForgotPasswordView, \
    UserPasswordResetDoneView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('/login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('/logout', LogoutView.as_view(), name='logout'),
    path('/register', RegisterView.as_view(), name='register'),
    path('/profile', ProfileView.as_view(), name='profile'),
    path('/wait-confirm-email', wait_confirm_email, name='confirm_email'),
    path('/confirm_email/<int:pk>', ConfirmPage.as_view(), name='confirmed_email'),
    path('/password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('/set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('/password-reset-sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('/password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='E-mail', unique=True)
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='user_avatar/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Подтверждение e-mail')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm, PasswordResetForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

class UserForgotPasswordForm(PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

users/views.py
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UserRegisterForm, UserProfileForm, UserForgotPasswordForm, UserSetNewPasswordForm
from users.models import User
from users.services import send_email_activate


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:confirm_email')

    def form_valid(self, form):
        if form.is_valid:
            fields = form.save()
            send_email_activate((fields.email,), fields.pk)
        return super().form_valid(form)


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def wait_confirm_email(request):
    context = {
        'title': 'Верификация пользователя'
    }

    return render(request, 'users/wait_confirm_email.html', context)


class ConfirmPage(TemplateView):
    template_name = 'users/confirmed_email.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        pk = context_data['pk']
        if User.objects.filter(pk=pk).exists():
            user = User.objects.get(pk=pk)
            user.is_active = True
            user.save()
        return context_data


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлена на ваш email'
    subject_template_name = 'users/email/password_subject_reset_mail.txt'
    email_template_name = 'users/email/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetDoneView(SuccessMessageMixin, PasswordResetDoneView):
    template_name = "users/user_password_reset_done.html"
    title = "Пароль сброшен"


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context

users/templates/users/confirmed_email.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h5>Почтовый адрес подтвержден</h5>
        <div class="pt-md-5">
            <a href="{% url 'catalog:catalog' %}" type="button" class="btn btn-lg btn-outline-primary" >Перейти в каталог</a>
        </div>
    </div>


        {% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h3>Вход на сайт</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="my-1">
                                <button type="submit" class="btn btn-primary">Войти</button>
                                <a href="{% url 'users:password_reset' %}" class="col-6">Я не помню свой пароль</a></div>
                            </div>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h3>Регистрация</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h3>Профиль пользователя</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="col-12">
        <form class="row" method="post" >
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h3>Запрос на восстановление пароля</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Восстановить пароль</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>

  {% endblock %}

users/templates/users/user_password_reset_done.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h4>Письмо с инструкциями по восстановлению пароля отправлено</h4>
        <p>Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.</p>
        <p>Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
    </div>


{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="col-12">
        <form class="row" method="post" >
            <div class="col-4"></div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h3>Установите новый пароль</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </form>
    </div>

  {% endblock %}

users/templates/users/wait_confirm_email.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h4> Верификация почтового адреса</h4>
        <p>Спасибо за регистрацию аккаунта на сайте. Для продолжения работы подтвердите вашу электронную почту, перейдя по ссылке из письма</p>
    </div>


        {% endblock %}