catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import home, contacts, CatalogDetailView, CatalogListView, BlogDetailView, BlogView, BlogUpdateView, \
    BlogCreateView, BlogDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contact'),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('product/<int:pk>/', cache_page(60)(CatalogDetailView.as_view()), name='product'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog_article',),
    path('blog/update/<str:slug>/', BlogUpdateView.as_view(), name='blog_update',),
    path('blog/delete/<str:slug>/', BlogDeleteView.as_view(), name='blog_delete',),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete',),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users', include('users.urls', namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, wait_confirm_email, ConfirmPage, UserForgotPasswordView, \
    UserPasswordResetDoneView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('/login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('/logout', LogoutView.as_view(), name='logout'),
    path('/register', RegisterView.as_view(), name='register'),
    path('/profile', ProfileView.as_view(), name='profile'),
    path('/wait-confirm-email', wait_confirm_email, name='confirm_email'),
    path('/confirm_email/<int:pk>', ConfirmPage.as_view(), name='confirmed_email'),
    path('/password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('/set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('/password-reset-sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('/password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

catalog/models.py
from datetime import datetime
from transliterate import slugify

from django.db import models

from users.models import User, NULLABLE


class Category(models.Model):

    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):

    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    preview = models.ImageField(upload_to='preview', default='preview/default.JPG', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория', **NULLABLE)
    price = models.FloatField(verbose_name='Цена')
    data_creating = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    data_updating = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения', **NULLABLE)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)
    is_public = models.BooleanField(default=False, verbose_name='опубликовано')

    def __str__(self):
        return f"{self.name}, {self.category}"


class Blog(models.Model):

    title_name = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(default=slugify(str(title_name)), max_length=150)
    content = models.TextField(verbose_name='Текст', **NULLABLE)
    preview = models.ImageField(upload_to='blog/preview', default='preview/default.JPG', verbose_name='Изображение')
    data_creating = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0)

    def add_view(self):
        self.view_count += 1
        return self.view_count

    def delete(self, *args, **kwargs):
        self.is_published = False
        self.save()

    def __str__(self):
        return f"{self.title_name}"


class ProductVersion(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт', related_name='version')
    version_number = models.PositiveIntegerField(verbose_name='Номер версии', **NULLABLE)
    version_name = models.CharField(max_length=50, verbose_name='Имя версии', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Активная версия')

    def __str__(self):
        return f'{self.version_number}'

catalog/forms.py
from django import forms

from catalog.models import Product, ProductVersion


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'preview', 'category', 'price', 'is_public',)

    def clean_description(self, forbidden_lists=forbidden_list):

        cleaned_data = self.cleaned_data['description']
        for word in forbidden_lists:
            if word in cleaned_data:
                raise forms.ValidationError('Недопустимое описание')
        return cleaned_data

    def clean_name(self, forbidden_lists=forbidden_list):

        cleaned_data = self.cleaned_data['name']
        for word in forbidden_lists:
            if word in cleaned_data:
                raise forms.ValidationError('Недопустимое название')
        return cleaned_data


class ProductVersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = ProductVersion
        fields = '__all__'

catalog/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.messages import success
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from pytils.translit import slugify

from catalog.forms import ProductForm, ProductVersionForm
from catalog.models import Product, Blog, ProductVersion
from catalog.services import get_category_cached
from config import settings


def home(request):
    product_list = Product.objects.all()
    context = {
        'product_list': product_list,
        'title': 'Каталог'
    }
    return render(request, 'catalog/home.html', context)


class CatalogListView(generic.ListView):
    model = Product
    extra_context = {
        'title': 'Каталог'
    }


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')

    context = {
        'title': 'Контакты'
    }

    return render(request, 'catalog/contacts.html', context)


class CatalogDetailView(generic.DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        context_data['category'] = get_category_cached(self.object.pk)
        return context_data


class BlogView(generic.ListView):
    model = Blog
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        queryset = queryset.order_by('-data_creating')
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blog

    def get_object(self, queryset=None):
        post = super().get_object()
        post.add_view()
        post.save()
        return post

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']

        return context_data


class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = Blog
    fields = ['title_name', 'content', 'preview']
    success_url = reverse_lazy('catalog:blog')
    extra_context = {
        'title': 'Написать статью'
    }

    def form_valid(self, form):
        if form.is_valid():
            fields = form.save(commit=False)
            fields.slug = slugify(form.cleaned_data['title_name'])
            fields.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Blog
    fields = ['title_name', 'content', 'preview']
    success_url = reverse_lazy('catalog:blog')
    extra_context = {
        'title': 'Редактировать статью'
    }


class BlogDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog')
    extra_context = {
        'title': 'Удалить статью'
    }


class ProductCreateView(LoginRequiredMixin, generic.CreateView):

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def form_valid(self, form):
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, ProductVersion, form=ProductVersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser or self.request.user.has_perm('catalog.change_product'):
            return self.object
        if self.object.created_by != self.request.user:
            raise Http404('Нет прав доступа')
        return self.object


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:catalog')
    permission_required = 'catalog.change_product'
    extra_context = {
        'title': 'Удалить продукт'
    }

catalog/templates/catalog/base.html
{% load static %}
{% load my_tags %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h2 class="my-0 mr-md-auto font-weight-normal">LEDforYOU</h2>
      {% if user.is_authenticated %}
          <h5 class="my-0 mr-md-5 font-weight-normal">{{user.email}}</h5>
      {% endif %}
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'catalog:catalog' %}">Каталог</a>
        <a class="p-2 text-dark" href="{% url 'catalog:blog' %}">Блог</a>
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'users:logout' %}">Выйти</a>
            <a class="p-2 text-dark" href="{% url 'users:profile' %}">Профиль</a>

        {% else %}
            <a class="p-2 text-dark" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 text-dark" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}

      </nav>
      <a class="btn btn-outline-primary" href="{% url 'catalog:contact' %}">Контакты</a>
    </div>

    {% block content %}
    {% endblock %}

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">

            <small class="d-block mb-3 text-muted">&copy; 2023 - {% current_year %}</small>
          </div>
        {% include 'catalog/includes/incl_bottom_menu.html' %}
        </div>
      </footer>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить статью "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'catalog:blog' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
  {% block content %}

      <div class="container">

          <div class="card-deck mb-3 text-center">

            <div class="card mb-4 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.title_name }}</h4>
              </div>

              <div class="card-body">
                <h2 class="card-title pricing-card-title">Кол-во просмотров: {{ object.view_count }} </h2>
                {% if object.preview %}
                  <div><img src='{% mediapath object.preview %}'  align="left" width="100%" height="100%"></div>
                {% else %}
                  <div><img src="/media/preview/default.JPG" align="left" width="100%" height="100%"></div>
                {% endif %}
                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ object.content }}</li>

                </ul>


                <p><b>Дата создания:</b> {{ object.data_creating }}</p>

                <a href="{% url 'catalog:blog' %}" type="button" class="btn btn-lg btn-block btn-outline-warning">Вернуться</a>
              </div>

            </div>

          </div>

      </div>
  {% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Написать статью в блог</h1>
    </div>

        <div class="container">

                <div class="col-lg-5 col-md-6 col-sm-12">
                    <div class="card mb-3 box-shadow">

                        <div class="card-body">
                            <form method="post" id="new_article" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="create-blog">{{ form.as_p }}</div>

                            </form>
                            <button type="submit" form="new_article" class="btn btn-lg btn-block btn-outline-primary">Опубликовать</button>
                            <a href="{% url 'catalog:blog' %}" type="button" class="btn btn-lg btn-block btn-outline-warning">Вернуться</a>
                        </div>

                    </div>

                </div>

        </div>

        {% endblock %}

                     <!--
                        <form method="post" id="new_article" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="title_name">Заголовок</label>
                                <input type="text" name="name" class="form-control" id="title_name" placeholder="Заголовок статьи" required>
                            </div>

                            <div class="mb-3">
                                <label for="content">Текст статьи</label>
                                <textarea type="text" name="message" class="form-control" id="content" placeholder="Текст статьи" required></textarea>
                            </div>

                          <div class="mb-3">
                                <label for="content">Изображение</label>
                                <input type="file" name="preview" class="form-control" id="preview"> </input>
                            </div>
                        </form>

                        <button type="submit" form="new_article" class="btn btn-lg btn-block btn-outline-primary">Опубликовать</button> -->

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Блог</h1>
      <p class="lead">Список статей в блоге</p>
    </div>


      <div class="container">
        <a href="{% url 'catalog:blog_create' %}" class="btn btn-lg btn-outline-primary">Создать статью</a>
        <p></p>
{% for post in object_list%}
          <div class="card-deck mb-3 text-center">

            <div class="card mb-10 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ post.title_name }}</h4>
              </div>

              <div class="card-body">

                {% if post.preview %}
                <p class="card-text">
                  <b>Количество просмотров:</b> {{ post.view_count }}
                </p>
                <p class="card-text">
                  <b>Дата публикации:</b> {{ post.data_creating }}
                </p>
                  <div><img src='{% mediapath post.preview %}'  align="left" width="100%" height="100%"></div>
                {% else %}
                  <div><img src="/media/preview/default.JPG" align="center"></div>
                {% endif %}

                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ post.content  | slice:"0:100"}}</li>

                </ul>
                <a href="{% url 'catalog:blog_article' slug=post.slug %}" type="button" class="btn btn-lg btn-block btn-outline-dark" >Читать статью</a>
                <a href="{% url 'catalog:blog_update' slug=post.slug  %}" type="button" class="btn btn-lg btn-block btn-outline-warning">Редактировать статью</a>
                <a href="{% url 'catalog:blog_delete' slug=post.slug  %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить статью</a>

              </div>
              <p></p>

            </div>

          </div>
{% endfor %}
      </div>
  {% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
  {% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Контакты</h1>
    </div>

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-5 col-md-6 col-sm-12">
                <div class="card mb-3 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Название</td>
                                <td>ИП Перфилов И.В.</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>6451209111</td>
                            </tr>
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>410036, Саратов, ул. Чкалова, 43\1</td>
                            </tr>
                            <tr>
                                <td class="w-25">ОГРНИП</td>
                                <td>1789654329</td>
                            </tr>
                            <tr>
                                <td class="w-25">Телефон</td>
                                <td>+7 (8452) 321-45-67</td>
                            </tr>
                            <tr>
                                <td class="w-25">E-mail</td>
                                <td>info@ledforyou.ru</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" id="feedback" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message" placeholder="Оставьте комментарий" required></textarea>
                            </div>
                        </form>

                        <button type="submit" form="feedback" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Каталог товаров</h1>
      <p class="lead">Ассортимент товаров для сборки медиаэкранов</p>
    </div>


      <div class="container">

          <div class="card-deck mb-3 text-center">
            {% for card in product_list%}
            <div class="card mb-4 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ card.name }}</h4>
              </div>

              <div class="card-body">
                <h1 class="card-title pricing-card-title">${{ card.price }} </h1>
                {% if card.preview %}
                  <div><a href="{% url 'catalog:product' pk=card.id %}"><img src='{% mediapath card.preview %}'  align="left" width="100%" height="100%"></a></div>
                {% else %}
                  <div><a href="{% url 'catalog:product' pk=card.id %}"><img src="/media/preview/default.JPG" align="left" width="100%" height="100%"></a></div>
                {% endif %}

                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ card.description | title | slice:"0:47" }}</li>

                </ul>
                <a href="{% url 'catalog:contact' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary" >Заказать</button></a>
              </div>

            </div>
    {% endfor %}
          </div>

      </div>
  {% endblock %}

catalog/templates/catalog/product_card.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
  {% block content %}

      <div class="container">

          <div class="card-deck mb-3 text-center">

            <div class="card mb-4 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
              </div>

              <div class="card-body">
                <h1 class="card-title pricing-card-title">${{ object.price }} </h1>
                {% if object.preview %}
                  <div><img src='{% mediapath object.preview %}'  align="left" width="100%" height="100%"></div>
                {% else %}
                  <div><img src="/media/preview/default.JPG" align="left" width="100%" height="100%"></div>
                {% endif %}
                <ul class="list-unstyled mt-3 mb-4">
                  <li><b>Описание:</b> {{ object.description | title }}</li>

                </ul>
                <p><b>Категория:</b> {{ object.category}}</p>

                <p><b>Дата создания:</b> {{ object.data_creating }}</p>
                <p><b>Дата редактирования:</b> {{ object.data_updating }}</p>
                <a href="{% url 'catalog:contact' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary" >Заказать</button></a>
              </div>

            </div>

          </div>

      </div>
  {% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
  {% block content %}

      <div class="container">

          <div class="card-deck mb-3 text-center">

            <div class="card mb-4 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
              </div>

              <div class="card-body">
                <h1 class="card-title pricing-card-title">${{ object.price }} </h1>
                {% if object.preview %}
                  <div><img src='{% mediapath object.preview %}'  align="left" width="100%" height="100%"></div>
                {% else %}
                  <div><img src="/media/preview/default.JPG" align="left" width="100%" height="100%"></div>
                {% endif %}
                <ul class="list-unstyled mt-3 mb-4">
                  <li><b>Описание:</b> {{ object.description | title }}</li>

                </ul>
                <p><b>Категория:</b> {{ object.category}}</p>

                <p><b>Дата создания:</b> {{ object.data_creating }}</p>
                <p><b>Дата редактирования:</b> {{ object.data_updating }}</p>
                {% if perms.catalog.change_product or product.created_by == request.user or user.is_superuser%}
                    <p><a href="{% url 'catalog:product_update' object.id %}"><button type="button" class="btn btn-lg btn-block btn-outline-warning" >Редактировать продукт</button></a></p>
                    <p><a href="{% url 'catalog:product_delete' object.id %}"><button type="button" class="btn btn-lg btn-block btn-outline-danger" >Удалить продукт</button></a></p>
                {% endif %}
                <p><a href="{% url 'catalog:catalog' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary" >Вернуться в каталог</button></a></p>

              </div>

            </div>

          </div>

      </div>
  {% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Каталог товаров</h1>
      <p class="lead">Ассортимент товаров для сборки медиаэкранов</p>
    </div>


      <div class="container">
          <a href="{% url 'catalog:product_create' %}" class="btn btn-lg btn-outline-primary">Добавить товар</a>
          <p></p>

          <div class="card-deck mb-3 text-center">
            {% for card in product_list%}
              {% if card.is_public %}
                <div class="card mb-4 box-shadow">

                  <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ card.name }}</h4>
                  </div>

                  <div class="card-body">
                    <h1 class="card-title pricing-card-title">${{ card.price }} </h1>
                    {% if card.preview %}
                      <div><a href="{% url 'catalog:product' pk=card.id %}"><img src='{% mediapath card.preview %}'  align="left" width="100%" height="100%"></a></div>
                    {% else %}
                      <div><a href="{% url 'catalog:product' pk=card.id %}"><img src="/media/preview/default.JPG" align="left" width="100%" height="100%"></a></div>
                    {% endif %}
                    {% for version in card.version.all %}
                      <p class="card-text"> {% if version.is_active %}Активная версия: {{ version }} {% endif %}</p>
                    {% endfor %}
                    <ul class="list-unstyled mt-3 mb-4">
                      <li>{{ card.description | title | slice:"0:47" }}</li>

                    </ul>
                    <a href="{% url 'catalog:contact' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary" >Заказать</button></a>
                  </div>

                </div>
            {% endif %}
    {% endfor %}
          </div>

      </div>
  {% endblock %}